FROM ubuntu:latest


RUN apt update 

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1


RUN apt-get install -y python3-opencv python3-pip vim-tiny mosquitto-clients libopencv-dev
RUN pip3 install paho-mqtt


WORKDIR /apps
#COPY face_detector.py face_detector.py
#COPY haarcascade_frontalface_default.xml haarcascade_frontalface_default.xml
CMD python3 ./face_detector.py


