FROM ubuntu:latest

RUN apt update 

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1


RUN apt-get install -y python3-opencv python3-pip vim-tiny mosquitto-clients libopencv-dev
RUN pip3 install paho-mqtt


WORKDIR /apps
#COPY mqtt_forwarder.py mqtt_forwarder.py
CMD python3 ./mqtt_forwarder.py
