apiVersion: apps/v1
kind: Deployment
metadata:
  name: facedetect-deployment
spec:
  selector:
    matchLabels:
      app: facedetect
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: facedetect
    spec:
      containers:
      - name: facedetect
        image: face_detector:v2
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        - mountPath: /apps
          name: apps
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
           path: /dev/video0
      - name: apps
        hostPath:
           path: /home/madhu/work/W251_HW/v3/week03/hw_kb
        
