apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttfwd-deployment
spec:
  selector:
    matchLabels:
      app: mqttforward
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mqttforward
    spec:
      containers:
      - name: mqttforward
        image: mqtt_forward:v2
        volumeMounts:
        - mountPath: /apps
          name: apps
#        securityContext:
#          privileged: true
      volumes:
      - name: apps
        hostPath:
           path: /home/madhu/work/W251_HW/v3/week03/hw_kb
